import React from 'react';
import { Link } from 'react-router-dom';

const PrivacyPolicyComponent = () => {
    return (
        <div className='bg-[#FFF5EB] py-[54px] md:py-[80px]'>
                <h1 className='text-[32px] md:text-6xl font-rubik text-primary-title uppercase text-center'>Privacy Policy</h1>
                <p className=' font-IBM text-center'>Last updated September 23rd, 2023</p>
                <div className='mx-3 md:mx-[150px]'>
                  <div>
                  <h3 className='text-[32px] font-IBM font-semibold text-stone-900 mt-[40px] md:mt-[48px]'>Lorem ipsum dolor sit amet</h3>
                    <p className='font-IBM font-medium'>Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. </p>

                    <h5 className=' font-IBM mt-[32px] text-lg font-medium '>1. Lorem ipsum dolor sit amet</h5>
                    <p className=' font-IBM mt-[18px]'>Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <div className=' ml-[24px] md:ml-[48px]'>
                        <p className=' font-IBM text-base mt-[18px]'>1.1 Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                        <p className=' font-IBM text-base mt-[18px]'>1.2 Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros <Link to={"/"} className='text-sky-500 underline'>semper massa quisque.</Link> </p>
                        <p className=' font-IBM text-base mt-[18px]'>1.3 Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                    </div>
                    <div>
                    <h5 className=' font-IBM mt-[32px] text-lg font-medium '>2. Lorem ipsum dolor sit amet</h5>
                    <p className=' font-IBM mt-[18px]'>Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <div className='ml-[24px] md:ml-[48px]'>
                        <p className=' font-IBM text-base mt-[18px]'>2.1 Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                        <p className=' font-IBM text-base mt-[18px]'>2.2 Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros <Link to={"/"} className='text-sky-500 underline'>semper massa quisque.</Link> </p>
                        <p className=' font-IBM text-base mt-[18px]'>2.3 Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                    </div>
                    </div>
                  </div>
                </div>
            </div>
    );
};

export default PrivacyPolicyComponent;