import React from 'react';

const TermsConditionsComponent = () => {
    return (
        <div className='bg-[#FFF5EB] py-[54px] md:py-[80px]'>
              <h1 className='text-[32px] md:text-6xl font-rubik text-primary-title uppercase text-center'>Terms & Conditions</h1>
              <p className=' font-IBM text-center'>Last updated September 23rd, 2023</p>
              <div className='mx-3 md:mx-[150px]'>
                <div>
                    <h1 className='text-[32px] text-stone-950 font-semibold font-IBM mt-[40px] md:mt-[48px]'>Interpretation and Definitions</h1>
                    <p className='font-IBM'>Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. </p>
                    <h4 className='text-2xl font-IBM uppercase text-stone-950'>Lorem ipsum dolor sit amet</h4>
                    <div>
                    <h5 className=' font-IBM mt-[32px] text-lg font-medium '>1. Lorem ipsum dolor sit amet</h5>
                    <p className=' font-IBM text-base mt-[18px]'>a) Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <p className=' font-IBM text-base mt-[18px]'>b) Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                    <p className=' font-IBM text-base mt-[18px]'>c) Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <p className=' font-IBM text-base mt-[18px]'>d) Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget </p>
                    </div>
                    <div>
                    <h5 className=' font-IBM mt-[32px] text-lg font-medium '>2. Lorem ipsum dolor sit amet</h5>
                    <p className=' font-IBM text-base mt-[18px]'>a) Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <p className=' font-IBM text-base mt-[18px]'>b) Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. </p>
                    <p className=' font-IBM text-base mt-[18px]'>c) Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget eros semper massa quisque.</p>
                    <p className=' font-IBM text-base mt-[18px]'>d) Convallis hendrerit mauris est ullamcorper gravida neque molestie. Rutrum lectus ipsum velit egestas congue adipiscing. A urna tempus pretium velit proin semper viverra pellentesque nulla. Lectus ac sodales ipsum nisi amet rutrum tellus tempor pretium. Commodo non augue ut aliquam et proin donec. Molestie non mauris sit posuere vitae. Ut tempor sit commodo neque.Lorem ipsum dolor sit amet consectetur. Gravida tempus morbi congue diam ut et odio. Duis sodales in sed nulla. Est enim amet vel sit enim nisi arcu. Amet nam amet ut id tempor adipiscing ultrices commodo velit. Tristique orci nullam habitasse tempor a scelerisque commodo. Sit quis enim proin netus neque porttitor mi bibendum. Cras sapien porta sagittis purus adipiscing tellus. Massa egestas ante nulla urna vel neque. Adipiscing faucibus facilisis gravida sem. Mauris scelerisque cras quam id. Mollis egestas quis quis imperdiet posuere sagittis integer quis. Nisl penatibus tempus arcu sit urna cursus eget. Arcu elementum malesuada eros condimentum eget </p>
                    </div>
                </div>
              </div>
        </div>
    );
};

export default TermsConditionsComponent;